using System.CodeDom.Compiler;
using System.Xml.Linq;

namespace CodeGen.Framework;

public sealed class AsyncCodeBuilder : IDisposable, IAsyncDisposable
{
    private readonly IndentedTextWriter outputTextWriter;
    private readonly XElement root;

    public AsyncCodeBuilder(IndentedTextWriter indentedTextWriter, string documentationFile)
    {
        this.outputTextWriter = indentedTextWriter;

        XDocument document = XDocument.Load(documentationFile);
        this.root = document.Root ?? throw new InvalidOperationException("No root element!");
    }

    public AsyncCodeBuilder(StreamWriter streamWriter, string documentationFile)
        : this(new IndentedTextWriter(streamWriter), documentationFile)
    {
    }

    public async Task BuildAsync(string className, string archSuffix, string @namespace)
    {
        await this.outputTextWriter.WriteLineAsync("/// <auto-generated />");
        await this.outputTextWriter.WriteLineAsync($"namespace SharpImmintrin;");
        await this.outputTextWriter.WriteLineAsync();

        await this.outputTextWriter.WriteLineAsync($"public static unsafe partial class CIntrinsic{archSuffix}{className}");
        await this.outputTextWriter.WriteLineAsync($"{{");

        HashSet<string> dynamicMembers = [];

        foreach (XElement assemblyOrMembers in root.Elements())
        {
            if (assemblyOrMembers.Name.LocalName == "members")
            {
                IEnumerable<XElement> elements = assemblyOrMembers.Elements();

                foreach (XElement member in elements)
                {
                    IEnumerable<XElement> childrenOfMember = member.Elements();
                    string memberName = member.Attribute("name")!.Value;

                    if (!memberName.Contains($".{className}."))
                        continue;

                    foreach (XElement innerDocumentationElement in childrenOfMember)
                    {
                        if (innerDocumentationElement.Name.LocalName == "summary")
                        {
                            IEnumerable<XElement> subTags = innerDocumentationElement.Elements();
                            int numParaTags = subTags.Count(x => x.Name.LocalName == "para");
                            if (numParaTags >= 2)
                            {
                                XElement firstParaTag = subTags.First();
                                string expandedMemberName = memberName.Replace($"M:{@namespace}", $"System.Runtime.Intrinsics.{archSuffix}");
                                string signature = firstParaTag.Value;
                                string escapeMember = expandedMemberName
                                    .Replace("{", "<")
                                    .Replace("}", ">");

                                signature = signature.Replace("const ", "").Replace("const", "");
                                signature = signature.Replace("unsigned int", "uint").Replace("unsigned __int64", "ulong");

                                if (!dynamicMembers.Add(signature))
                                {
                                    Console.WriteLine($"[{className}] Found duplicate member: " + signature);
                                    continue;
                                }

                                await this.outputTextWriter.WriteLineAsync("    /// <summary>");
                                await this.outputTextWriter.WriteLineAsync($"    ///     See <see cref=\"{expandedMemberName}\" />");
                                await this.outputTextWriter.WriteLineAsync("    /// </summary>");
                                await this.outputTextWriter.WriteLineAsync($"    public static {signature}");
                                await this.outputTextWriter.WriteLineAsync($"        => throw new InvalidOperationException(\"Replace with {escapeMember}\");");
                            }
                        }
                    }
                }
            }
        }

        await this.outputTextWriter.WriteLineAsync($"}}");
    }

    public static async Task CreateAsync(string[] classes, string architectureSuffix, string @namespace)
    {
        foreach (string cl in classes)
        {
            using var outputFile = File.Open(architectureSuffix + "_" + cl + ".generated.cs", FileMode.Create);
            using var streamWriter = new StreamWriter(outputFile);

            // -> net10.0 -> Debug -> bin -> Generators -> namespace -> bin -> Debug -> net10.0 -> namespace.xml
            string xml = Path.Combine("..", "..", "..", "..", @namespace, "bin", "Debug", "net10.0", $"{@namespace}.xml");

            using AsyncCodeBuilder asyncCodeBuilder = new(streamWriter, xml);
            await asyncCodeBuilder.BuildAsync(cl, architectureSuffix, @namespace);
        }
    }

    public void Dispose()
    {
        this.outputTextWriter.Dispose();
        GC.SuppressFinalize(this);
    }

    public async ValueTask DisposeAsync()
    {
        await this.outputTextWriter.DisposeAsync();
        GC.SuppressFinalize(this);
    }
}
